### ISSUE TITLE
should plugins have control over stack trace limit

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/cute-stack#7]
we should probably have a way for plugins to set their own stack trace limit defaults, 
different use cases may call for different limits

**Comment by bahmutov** [comment]
Plugins can use .filter method to limit output

**Comment by davidmarkclements** [comment]
but not increase it - unless it edits Error.stackTraceLimit directly

this raises the question should we just be done with it and set Error.stackTraceLimit to Infinity then .filter can limit it (which still seems a little raw) or keep it at node's default of 10 but allow plugins to set their own defaults via cute stack

**Comment by bahmutov** [comment]
I would not allow plugins to set the limit - mainly because the user probably knows better, that is why it is the second argument to cute-stack

**Comment by davidmarkclements** [comment]
ok yah leave as config option - good call
